name: Test Compatibility

on:
  workflow_dispatch:

jobs:
  test-compatibility:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
        php:
          # - "8.2"
          - "8.4"

    steps:
      - name: Install tools
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libxml2-utils

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate docsets
        run: |
          ./generate.sh es

      - name: Test find -regex
        run: |
          for docset in output/*.docset; do
            set -x
            find "$docset" -type f -regex '.*/[0-9a-f]\{13\}\.html$'
            find "$docset" -type f -regex '.*/[0-9a-f]{13}\.html$'
            set +x
          done

      # - name: Test get_docset_version()
      #   run: |
      #     source ./lib/common.sh
      #     for docset in output/*.docset; do
      #       version=$(get_docset_version "$docset")
      #       echo "$docset version: $version"
      #     done
